#!/usr/bin/env python
#vim: set filetype=python

import subprocess
import sys
import tempfile

def getline(prefix):
    line = sys.stdin.readline()
    assert line.startswith(prefix)
    return line[len(prefix)+2:-2].replace(r'\n', '\n')

def linetofile(prefix):
    f    = tempfile.NamedTemporaryFile(mode="w")
    f.write(getline(prefix))
    f.flush()
    return f

def hline():
    sys.stdout.write("-" * 20 + "\n")

while True:
    expected = linetofile("expected:")
    butgot   = linetofile(" but got:")

    hline()
    proc = subprocess.Popen(["wdiff", expected.name, butgot.name])
    proc.wait()
    sys.stdout.write("\n")
    hline()
