#!/usr/bin/env python
#vim: set filetype=python

import subprocess
import sys
import os

proc = subprocess.Popen("make", stdout=subprocess.PIPE, stderr=subprocess.PIPE)
out, err = proc.communicate()
sys.stdout.write(out)

res = []
notify = None
for line in err.split("\n"):
    if line.startswith("Ocram/Test"):
        res.append("test/" + line)
        if not notify: notify = line  
    elif line.startswith("Ocram/"):
        res.append("src/" + line)
        if not notify: notify = line  
    elif line.startswith("Cases:"):
        res.append(line)
        if not notify: notify = line  
    else:
        res.append(line)

res_str = "\n".join(res)
sys.stdout.write(res_str)
open("./.quickfix", "w").write(res_str)

def notify_results(text):
    if text.endswith("Errors: 0  Failures: 0"):
        color = "green"
    else:
        color = "red"

    cmd = ["/usr/bin/osd_cat", "-A", "right", "-d", "2", "-c", color]

    if os.fork() == 0:
        subprocess.Popen(cmd, stdin=subprocess.PIPE).communicate(text)

notify_results(notify)
