all: pal
PROJECT_SOURCEFILES += app.c common.c rpc.c cooja.c
APPS=

CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"
CFLAGS += -I$(ROOT)/applications/contiki
SMALL=1

WITH_UIP6=1
UIP_CONF_IPV6=1
UIP_CONF_RPL=1

CONTIKI=/home/blinded//scm/contiki
include $(CONTIKI)/Makefile.include
