#ifndef OOYAILOOYUSUUFEIROOV
#define OOYAILOOYUSUUFEIROOV

#define CALL_INTERVAL (10 * CLOCK_SECOND)
#define SLOW_SENSOR_DELAY (5 * CLOCK_SECOND)

#define UDP_CLIENT_PORT UIP_HTONS(8765)
#define UDP_SERVER_PORT UIP_HTONS(5678)

#endif

