all: pal
PROJECT_SOURCEFILES += app.c coap.c debug.c
APPS =

CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"
CFLAGS += -I$(ROOT)/applications/contiki
SMALL=1

WITH_UIP6=1
UIP_CONF_IPV6=1
WITH_COAP=7
UIP_CONF_RPL=1


CFLAGS += -DREST=coap_rest_implementation
CFLAGS += -DUIP_CONF_TCP=0

CONTIKI=/home/alex/scm/contiki
include $(CONTIKI)/Makefile.include
