#!/usr/bin/env python

import sys
import fileinput
import subprocess
import os

expected = []
got = []

for line in fileinput.input():
	if line.startswith("expected:"):
		(pre, code, post) = line.split('"')
		expected.append(code)
	if line.startswith(" but got:"):
		(pre, code, post) = line.split('"')
		got.append(code)
		
assert len(expected) == len(got), str(expected) + "\n" + str(got)

def paste(name, code):
	f = open(name, "w")
	f.write(code.replace(r'\n', '\n'))
	f.close()

inf = "/tmp/infile.c"
outf = "/tmp/outfile.c"

for (ins, outs) in zip(got, expected):
	print "----- diff"
	paste(inf, ins)
	paste(outf, outs)
	
	proc = subprocess.Popen(["wdiff", inf, outf])
	proc.wait()
