all: app server

CONTIKI=/home/alex/scm/contiki
CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"

WITH_UIP6=1
UIP_CONF_IPV6=1
WITH_COAP=7
SMALL=1

CFLAGS += -DUIP_CONF_IPV6_RPL=1
CFLAGS += -DWITH_COAP=7
CFLAGS += -DREST=coap_rest_implementation
CFLAGS += -DUIP_CONF_TCP=0
CFLAGS += -I$(ROOT)/applications/contiki/

APPS += er-coap-07
APPS += erbium

include $(CONTIKI)/Makefile.include
