all: pal
PROJECT_SOURCEFILES += app.c common.c rpc.c debug.c
CFLAGS += -I$(ROOT)/applications/contiki

APPS=
CONTIKI=/home/alex/scm/contiki
CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"
SMALL=1

WITH_UIP6=1
UIP_CONF_IPV6=1
UIP_CONF_RPL=1

include $(CONTIKI)/Makefile.include
