#ifndef AHJAHNEISIEYOHYAEWOO
#define AHJAHNEISIEYOHYAEWOO

#define UDP_CLIENT_PORT 8765
#define UDP_SERVER_PORT 5678

#define DT_SEND (127 * CLOCK_SECOND)
#define DT_SOURCE (101 * CLOCK_SECOND)
#define DT_COLLECT (23 * CLOCK_SECOND)

#define MAX_NUMBEROF_VALUES 100

#endif
