all: pal
APPS=
CONTIKI=/home/alex/scm/contiki/

PROJECT_SOURCEFILES += app.c

WITH_UIP6=1
UIP_CONF_IPV6=1
CFLAGS+= -DUIP_CONF_IPV6_RPL
CFLAGS += -I$(ROOT)/applications/contiki

SMALL=1

include $(CONTIKI)/Makefile.include
