all: server
PROJECT_SOURCEFILES +=
APPS += er-coap-07 erbium

CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"
CFLAGS += -I$(ROOT)/applications/contiki/
SMALL=1

WITH_UIP6=1
UIP_CONF_IPV6=1
UIP_CONF_RPL=1
WITH_COAP=7

CFLAGS += -DREST=coap_rest_implementation
CFLAGS += -DUIP_CONF_TCP=0

CONTIKI=/home/blinded//scm/contiki
include $(CONTIKI)/Makefile.include
